### ISSUE TITLE
大佬求助

### ISSUE THREAD

**Issue by Daybreak000** [LuffysMan/image_text_recog#1]
大佬，你好！我是一名本科生，真正研究图像文本识别的算法，看到你的代码，我下载并学习了，但是遇到了困难，似乎代码并不完整，请问你后面做了完整的代码工作吗？非常渴望得到你的指导，能上传完整代码吗？非常感谢🙏

**Comment by LuffysMan** [comment]
谢谢关注. 这个repository也是我初学图像文本识别做的尝试, 里面的方法比较旧, 代码也远远不够不完善. 有参考价值的东西并不多, 可能踩过的一些坑还有点参考D:).    
   很可惜我后来没有继续进行这方便的研究了.  学习图像文本识别的话建议找近年来顶级会议发表的论文, 和它们对应的开源代码, 这些已发表工作比较完整. 
   比如这个repository总结的看起来还不错, 从dataset, paper都有 [link](https://github.com/HCIILAB/Scene-Text-Recognition).
